overrides:
  fast-uri: 3.1.8
engineStrict: true
saveExact: true
ignoreScripts: true
minimumReleaseAge: 10080
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@nais/apm@0.7.2'
