apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-utbetalingsportalen-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-utbetalingsportalen"} == 0
          for: 5m
          annotations:
            action: "Sjek hvorfor applikasjonen er nede"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_utbetalingsportalen_type: sokos-utbetalingsportalen
            alert_type: custom

        - alert: Applikasjonen har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-utbetalingsportalen"}[5m])) by (container) > 2
          for: 5m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "App {{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_utbetalingsportalen_type: sokos-utbetalingsportalen
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-utbetalingsportalen-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-utbetalingsportalen-slack
spec:
  receivers:
    - name: sokos-utbetalingsportalen-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-dev'
          iconEmoji: ':alert:'
          username: 'Alert dev-gcp'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_utbetalingsportalen_type"
        matchType: "="
        value: "sokos-utbetalingsportalen"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-utbetalingsportalen-receiver
    repeatInterval: 5m
