apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: "/internal/metrics"
  replicas:
    min: 2
    max: 2
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "f49b797d-600d-46da-8061-7746e48d1aca" # 0000-GA-SOKOS-MF-SPK-MOTTAK-ADMIN
          - id: "6c93762e-ea37-4043-919f-3a758a136943" # 0000-GA-SOKOS-MF-Skattekort-READ
          - id: "25723642-e1da-4d15-87ce-8c4d2b87e33a" # 0000-GA-SOKOS-MF-PosteringSok-READ
          - id: "bb9c7baf-768b-4e84-816c-f10d0a6c7d25" # 0000-GA-SOKOS-MF-KRP-READ
          - id: "e1635067-dfc9-4fb8-8405-d50e9672cf5c" # 0000-GA-SOKOS-MF-KRO-READ
          - id: "f8919276-46bf-43a2-a9cb-9a5c5f9c8e16" # 0000-GA-SOKOS-MF-UTBETALING
          - id: "de776092-a8ed-46a2-be5e-ec2eae4dcf2b" # 0000-GA-SOKOS-MF-RESENDING-BANK-READ
          - id: "08723132-a7ba-40eb-a6f4-0a9247f230d2" # 0000-GA-SOKOS-MF-BUNTKONTROLL-READ
          - id: "ad41e055-af0c-4a26-a31c-c51d6ea236cd" # 0000-CA-SOKOS-MF-MELDINGSFLYT-READ
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-up-ors-api
        - application: sokos-up-kontoregister-api
      external:
        - host: sokos-skattekort-person.prod-fss-pub.nais.io
        - host: sokos-ur-iso.prod-fss-pub.nais.io
        - host: sokos-spk-mottak.prod-fss-pub.nais.io
        - host: sokos-meldingingsflyt.prod-fss-pub.nais.io
        - host: sokos-utbetaling-api.prod-fss-pub.nais.io
  ingresses:
    - "https://utbetalingsportalen.intern.nav.no"
    - "https://utbetalingsportalen.ansatt.nav.no"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  env:
    # sokos-up-ors-api
    - name: SOKOS_UP_ORS_API
      value: http://sokos-up-ors-api
    - name: SOKOS_UP_ORS_API_AUDIENCE
      value: api://prod-gcp.okonomi.sokos-up-ors-api/.default
    - name: SOKOS_UP_ORS_API_PROXY
      value: "/up-ors-api"

    # sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API
      value: http://sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API_AUDIENCE
      value: api://prod-gcp.okonomi.sokos-up-kontoregister-api/.default
    - name: SOKOS_KONTOREGISTER_API_PROXY
      value: "/up-kr-api"

    # Skattekort
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: https://sokos-skattekort-person.prod-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_PERSON_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-skattekort-person/.default
    - name: SOKOS_SKATTEKORT_PROXY
      value: "/skattekort-api"

    # sokos-ur-iso
    - name: SOKOS_UR_ISO
      value: https://sokos-ur-iso.prod-fss-pub.nais.io
    - name: SOKOS_UR_ISO_AUDIENCE
      value: api://prod-fss.okonomi.sokos-ur-iso/.default
    - name: SOKOS_UR_ISO_PROXY
      value: "/sokos-ur-iso"

    # SPK-Mottak
    - name: SOKOS_SPK_MOTTAK_API
      value: https://sokos-spk-mottak.prod-fss-pub.nais.io
    - name: SOKOS_SPK_MOTTAK_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-spk-mottak/.default
    - name: SOKOS_SPK_MOTTAK_PROXY
      value: "/spk-mottak-api"

    # up-meldingsflyt-api
    - name: SOKOS_MELDINGSFLYT_API
      value: https://sokos-betsys.prod-fss-pub.nais.io
    - name: SOKOS_MELDINGSFLYT_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-betsys/.default
    - name: SOKOS_MELDINGSFLYT_API_PROXY
      value: "/up-meldingsflyt-api"

    # sokos-utbetaling-api
    - name: SOKOS_UTBETALING_API
      value: https://sokos-utbetaling-api.prod-fss-pub.nais.io
    - name: SOKOS_UTBETALING_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-utbetaling-api/.default
    - name: SOKOS_UTBETALING_API_PROXY
      value: "/sokos-utbetaling-api"
