apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /api/internal/metrics
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "0e58dc41-7c57-4b79-a8c7-d0caec129e53" # 0000-GA-SOKOS-MF-SPK-MOTTAK-ADMIN
          - id: "e0023d91-26bc-4d5d-95ba-3148b6123afc" # 0000-GA-SOKOS-MF-OppdragsInfo-READ
          - id: "0de8d01f-8ad0-4391-841c-55392956bc17" # 0000-GA-SOKOS-MF-Attestasjon
          - id: "48a80bbb-be45-4ef6-aab8-21604f057f47" # 0000-GA-SOKOS-MF-Venteregister
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/internal/*
  accessPolicy:
    outbound:
      external:
        - host: sokos-oppdrag-qx.dev-fss-pub.nais.io
        - host: sokos-spk-mottak-qx.dev-fss-pub.nais.io
  ingresses:
    - "https://utbetalingsportalen-qx.intern.dev.nav.no"
    - "https://utbetalingsportalen-qx.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  env:

    - name: UTBETALINGSPORTALEN_URL
      value: utbetalingsportalen-qx.intern.dev.nav.no
    - name: UTBETALINGSPORTALEN_ENVIRONMENT
      value: qx

    # sokos-nav-oppdrag
    - name: SOKOS_OPPDRAG_API
      value: https://sokos-oppdrag-qx.dev-fss-pub.nais.io
    - name: SOKOS_OPPDRAG_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-oppdrag-qx/.default
    - name: SOKOS_OPPDRAG_PROXY
      value: "/oppdrag-api"

    # SPK-Mottak
    - name: SOKOS_SPK_MOTTAK_API
      value: https://sokos-spk-mottak-qx.dev-fss-pub.nais.io
    - name: SOKOS_SPK_MOTTAK_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-spk-mottak-qx/.default
    - name: SOKOS_SPK_MOTTAK_PROXY
      value: "/spk-mottak-api"
