apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /api/internal/metrics
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "f49b797d-600d-46da-8061-7746e48d1aca" # 0000-CA-SOKOS-MF-SPK-Mottak-ADMIN
          - id: "40ee7ce5-7ec8-405e-b2ea-951401c2633e" # 0000-CA-SOKOS-MF-ORS-READ
          - id: "bb9c7baf-768b-4e84-816c-f10d0a6c7d25" # 0000-GA-SOKOS-MF-KRP-READ
          - id: "e1635067-dfc9-4fb8-8405-d50e9672cf5c" # 0000-GA-SOKOS-MF-KRO-READ
          - id: "f8919276-46bf-43a2-a9cb-9a5c5f9c8e16" # 0000-GA-SOKOS-MF-Utbetaling
          - id: "072fb5d2-1cf5-4af2-8ce1-2a2585b9f0ce" # 0000-CA-SOKOS-MF-Resending-Bank-READ
          - id: "3309383f-4b8f-4778-99c1-311dc75bc482" # 0000-CA-SOKOS-MF-Buntkontroll-READ
          - id: "d192b937-5da1-46f5-b460-a3a5a2a63712" # 0000-CA-SOKOS-MF-Retur-fra-bank
          - id: "9c5b24f2-5e01-4966-adaf-bc9fb6410a32" # 0000-CA-SOKOS-MF-OPPGJORSRAPPORTER
          - id: "ad41e055-af0c-4a26-a31c-c51d6ea236cd" # 0000-CA-SOKOS-MF-Meldingsflyt-READ
          - id: "b37d0866-fae3-43c7-abd4-91cf485852c5" # 0000-CA-SOKOS-MF-Attestasjon
          - id: "f3d2cfe1-f437-412f-9165-075cb3d27a58" # 0000-CA-SOKOS-MF-Oppdragsinfo
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-up-ors-api
        - application: sokos-up-kontoregister-api
        - application: sokos-retur-fra-bank-api
        - application: sokos-skattekort
        - application: logging
          namespace: nais-system
      external:
        - host: sokos-oppdrag.prod-fss-pub.nais.io
        - host: sokos-ur-iso.prod-fss-pub.nais.io
        - host: sokos-spk-mottak.prod-fss-pub.nais.io
        - host: sokos-meldingingsflyt.prod-fss-pub.nais.io
        - host: sokos-utbetaling-api.prod-fss-pub.nais.io
  ingresses:
    - "https://utbetalingsportalen.intern.nav.no"
    - "https://utbetalingsportalen.ansatt.nav.no"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  env:

    # sokos-utbetalingsportalen
    - name: UMAMI_SPORINGSKODE
      value: "e1b661e6-a812-4433-a1e7-4648212fddfe"

    # sokos-skattekort (Backend)
    - name: SOKOS_SKATTEKORT_API
      value: http://sokos-skattekort
    - name: SOKOS_SKATTEKORT_API_AUDIENCE
      value: api://prod-gcp.okonomi.sokos-skattekort/.default
    - name: SOKOS_SKATTEKORT_API_PROXY
      value: "/sokos-skattekort"

    # sokos-up-ors-api (Backend)
    - name: SOKOS_UP_ORS_API
      value: http://sokos-up-ors-api
    - name: SOKOS_UP_ORS_API_AUDIENCE
      value: api://prod-gcp.okonomi.sokos-up-ors-api/.default
    - name: SOKOS_UP_ORS_API_PROXY
      value: "/up-ors-api"

    # sokos-up-kontoregister-api (Backend)
    - name: SOKOS_KONTOREGISTER_API
      value: http://sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API_AUDIENCE
      value: api://prod-gcp.okonomi.sokos-up-kontoregister-api/.default
    - name: SOKOS_KONTOREGISTER_API_PROXY
      value: "/up-kr-api"

    # sokos-ur-iso (Backend)
    - name: SOKOS_UR_ISO_API
      value: https://sokos-ur-iso.prod-fss-pub.nais.io
    - name: SOKOS_UR_ISO_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-ur-iso/.default
    - name: SOKOS_UR_ISO_API_PROXY
      value: "/sokos-ur-iso"

    # sokos-spk-mottak (Backend)
    - name: SOKOS_SPK_MOTTAK_API
      value: https://sokos-spk-mottak.prod-fss-pub.nais.io
    - name: SOKOS_SPK_MOTTAK_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-spk-mottak/.default
    - name: SOKOS_SPK_MOTTAK_API_PROXY
      value: "/spk-mottak-api"

    # sokos-oppdrag (Backend)
    - name: SOKOS_OPPDRAG_API
      value: https://sokos-oppdrag.prod-fss-pub.nais.io
    - name: SOKOS_OPPDRAG_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-oppdrag/.default
    - name: SOKOS_OPPDRAG_API_PROXY
      value: "/oppdrag-api"

    # up-meldingsflyt-api (Backend)
    - name: SOKOS_MELDINGSFLYT_API
      value: https://sokos-betsys.prod-fss-pub.nais.io
    - name: SOKOS_MELDINGSFLYT_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-betsys/.default
    - name: SOKOS_MELDINGSFLYT_API_PROXY
      value: "/up-meldingsflyt-api"

    # sokos-utbetaling-api (Backend)
    - name: SOKOS_UTBETALING_API
      value: https://sokos-utbetaling-api.prod-fss-pub.nais.io
    - name: SOKOS_UTBETALING_API_AUDIENCE
      value: api://prod-fss.okonomi.sokos-utbetaling-api/.default
    - name: SOKOS_UTBETALING_API_PROXY
      value: "/sokos-utbetaling-api"

    # sokos-retur-fra-bank-api (Backend)
    - name: SOKOS_RETUR_FRA_BANK_API
      value: http://sokos-retur-fra-bank-api
    - name: SOKOS_RETUR_FRA_BANK_API_AUDIENCE
      value: api://prod-gcp.okonomi.sokos-retur-fra-bank-api/.default
    - name: SOKOS_RETUR_FRA_BANK_API_PROXY
      value: "/sokos-retur-fra-bank-api"

    # sokos-up-oppgjorsrapporter (Frontend)
    - name: SOKOS_UP_OPPGJORSRAPPORTER_URL
      value: http://sokos-up-oppgjorsrapporter.oppgjorsrapporter
    - name: SOKOS_UP_OPPGJORSRAPPORTER_AUDIENCE
      value: api://prod-gcp.oppgjorsrapporter.sokos-up-oppgjorsrapporter/.default
