apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utbetalingsportalen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /api/internal/metrics
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "1b717a23-d376-471c-9fc6-356299fadc2b" # 0000-GA-SOKOS-MF-Mikrofrontend-READ
          - id: "0e58dc41-7c57-4b79-a8c7-d0caec129e53" # 0000-GA-SOKOS-MF-SPK-Mottak-ADMIN
          - id: "a13b4176-e328-4e1c-b181-ff676a7146b1" # 0000-GA-SOKOS-MF-Skattekort-READ
          - id: "b01fb216-fcb3-4ede-b7da-71fffe859763" # 0000-GA-SOKOS-MF-ORS-READ
          - id: "98146b9a-1891-44e3-9b61-92130c2fcd8b" # 0000-GA-SOKOS-MF-KRP-READ
          - id: "e0023d91-26bc-4d5d-95ba-3148b6123afc" # 0000-GA-SOKOS-MF-OppdragsInfo-READ
          - id: "0de8d01f-8ad0-4391-841c-55392956bc17" # 0000-GA-SOKOS-MF-Attestasjon
          - id: "391bec9e-e71e-42cb-a030-56c394dd13fd" # 0000-GA-SOKOS-MF-Resending-Bank-READ
          - id: "bdcedce3-dab5-4b68-b1d3-8625cd0d3b55" # 0000-GA-SOKOS-MF-KRO-READ
          - id: "138d21fb-4e96-46d6-91e4-e3926aa349e5" # 0000-GA-SOKOS-MF-Utbetaling
          - id: "3bc37bf2-8e76-407c-ad4a-d2c79edc241e" # 0000-GA-SOKOS-MF-Buntkontroll-READ
          - id: "48a80bbb-be45-4ef6-aab8-21604f057f47" # 0000-GA-SOKOS-MF-Venteregister
          - id: "2020a765-ffae-4042-b4cc-2a5a783a3ec5" # 0000-CA-SOKOS-MF-Meldingsflyt-READ
          - id: "7e0c2ad1-d0e7-4fa8-8169-7a9d68435644" # 0000-GA-SOKOS-MF-Fastedata
          - id: "2477057d-7f80-4517-a885-20c948bf0367" # 0000-GA-SOKOS-MF-DARE-POC
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/internal/*
  accessPolicy:
    outbound:
      rules:
        - application: sokos-up-ors-api
        - application: sokos-up-kontoregister-api
      external:
        - host: sokos-skattekort-person.dev-fss-pub.nais.io
        - host: sokos-oppdrag.dev-fss-pub.nais.io
        - host: sokos-ur-iso.dev-fss-pub.nais.io
        - host: sokos-utbetaling-api.dev-fss-pub.nais.io
        - host: sokos-spk-mottak.dev-fss-pub.nais.io
        - host: sokos-betsys.dev-fss-pub.nais.io
  ingresses:
    - "https://utbetalingsportalen.intern.dev.nav.no"
    - "https://utbetalingsportalen.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  env:

    - name: UTBETALINGSPORTALEN_URL
      value: utbetalingsportalen.intern.dev.nav.no
    - name: UTBETALINGSPORTALEN_ENVIRONMENT
      value: Q1

    # sokos-up-ors-api
    - name: SOKOS_UP_ORS_API
      value: http://sokos-up-ors-api
    - name: SOKOS_UP_ORS_API_AUDIENCE
      value: api://dev-gcp.okonomi.sokos-up-ors-api/.default
    - name: SOKOS_UP_ORS_API_PROXY
      value: "/up-ors-api"

    # sokos-skattekort-person
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: https://sokos-skattekort-person.dev-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_PERSON_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-skattekort-person/.default
    - name: SOKOS_SKATTEKORT_PERSON_API_PROXY
      value: "/skattekort-api"

    # sokos-spk-mottak
    - name: SOKOS_SPK_MOTTAK_API
      value: https://sokos-spk-mottak.dev-fss-pub.nais.io
    - name: SOKOS_SPK_MOTTAK_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-spk-mottak/.default
    - name: SOKOS_SPK_MOTTAK_API_PROXY
      value: "/spk-mottak-api"

    # sokos-oppdrag
    - name: SOKOS_OPPDRAG_API
      value: https://sokos-oppdrag.dev-fss-pub.nais.io
    - name: SOKOS_OPPDRAG_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-oppdrag/.default
    - name: SOKOS_OPPDRAG_API_PROXY
      value: "/oppdrag-api"

    # sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API
      value: http://sokos-up-kontoregister-api
    - name: SOKOS_KONTOREGISTER_API_AUDIENCE
      value: api://dev-gcp.okonomi.sokos-up-kontoregister-api/.default
    - name: SOKOS_KONTOREGISTER_API_PROXY
      value: "/up-kr-api"

    # sokos-ur-iso
    - name: SOKOS_UR_ISO_API
      value: https://sokos-ur-iso.dev-fss-pub.nais.io
    - name: SOKOS_UR_ISO_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-ur-iso/.default
    - name: SOKOS_UR_ISO_API_PROXY
      value: "/sokos-ur-iso"

    # sokos-utbetaling-api
    - name: SOKOS_UTBETALING_API
      value: https://sokos-utbetaling-api.dev-fss-pub.nais.io
    - name: SOKOS_UTBETALING_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-utbetaling-api/.default
    - name: SOKOS_UTBETALING_API_PROXY
      value: "/sokos-utbetaling-api"

    # up-meldingsflyt-api
    - name: SOKOS_MELDINGSFLYT_API
      value: https://sokos-betsys.dev-fss-pub.nais.io
    - name: SOKOS_MELDINGSFLYT_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-betsys/.default
    - name: SOKOS_MELDINGSFLYT_API_PROXY
      value: "/up-meldingsflyt-api"

    # umami
    - name: UMAMI_SPORINGSKODE
      value: "e174f8d8-4082-4cb0-8280-b992d0a47901"
