name: Sikkerhet

on:
  workflow_run:
    workflows: ["Deploy til dev og prod"]
    types:
      - completed
  schedule:
    - cron: '0 6 * * *'

env:
  IMAGE_LATEST: ghcr.io/${{ github.repository }}:latest
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  app-dependencies-vulnerabilities:
    name: Skanner applikasjon for sårbarheter
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kjører Snyk for å sjekke sårbarheter
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --org=team-mob --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git

  docker-image-vulnerabilities:
    name: Skanner docker image for sårbarheter
    needs: app-dependencies-vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Logger på Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ env.GITHUB_TOKEN }}
      - name: Sjekker ut repo
        uses: actions/checkout@v3
      - run: docker pull ${{ env.IMAGE_LATEST }}
      - name: Skanner docker image for sårbarheter
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_LATEST }}
          args: --file=Dockerfile --severity-threshold=high

  reportFailure:
    name: Slack notifikasjon bygg feiler
    needs: [ app-dependencies-vulnerabilities, docker-image-vulnerabilities ]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sender notifikasjon til Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: team-mob-workflow
          SLACK_COLOR: '#ff0000'
          SLACK_ICON: https://user-images.githubusercontent.com/29889280/178134303-4556873f-b2d6-46a0-b5af-a587b0fabb96.png
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: 'Sårbarhetstester feilet! :ghost:'
          SLACK_USERNAME: workflowBot
          MSG_MINIMAL: actions url,commit
          SLACK_FOOTER: 'team-mob'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}