name: Kjør ende-til-ende-tester ved pull-request

on:
  pull_request:

jobs:
  should-run-end-to-end-tests:
    if: github.repository != 'navikt/dittnav' && github.repository != 'navikt/dittnav-eventer-modia'
      && github.repository != 'navikt/dittnav-kafka-backup-reader' && github.repository != 'navikt/dittnav-nightly-usage-statistics-reporter'
        && github.repository != 'navikt/innloggingsstatus' && github.repository != 'navikt/pb-workflow-authority'
        && github.repository != 'navikt/dittnav-periodic-metrics-reporter' && github.repository != 'navikt/pb-oidc-provider-gui'
        && github.repository != 'navikt/mine-saker' && github.repository != 'navikt/mine-saker-api'
        && github.repository != 'navikt/tms-personalia-api' && github.repository != 'navikt/tms-min-side' && github.repository != 'navikt/tms-min-side-bunn'
        && github.repository != 'navikt/tms-min-side-topp' && github.repository != 'navikt/tms-utbetalingsoversikt-api' && github.repository != 'navikt/tms-innloggingsinfo-api'
        && github.repository != 'navikt/tms-shell' && github.repository != 'navikt/utbetalingsoversikt'
        && github.repository != 'navikt/innloggingsinfo' && github.repository != 'navikt/tms-min-side-proxy'
        && github.repository != 'navikt/tms-min-side-utbetalingsoversikt' && github.repository != 'navikt/tms-min-side-oversikt'
        && github.repository != 'navikt/tms-min-side-varslinger' && github.repository != 'navikt/tms-ettersende'
        && github.repository != 'navikt/tms-min-side-tjenester'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  run-end-to-end-tests:
    needs: should-run-end-to-end-tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Sjekk ut koden for dette repo-et'
        uses: actions/checkout@v2

      - name: 'Sjekk ut dittnav-docker-compose'
        uses: actions/checkout@v2
        with:
          repository: navikt/dittnav-docker-compose
          path: dittnav-docker-compose
          token: ${{ secrets.READER_TOKEN }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.READER_TOKEN }}

      - name: 'Pull dittnav-docker-compose'
        run: |
          cd dittnav-docker-compose
          docker-compose pull
          cd ..

      - name: 'Docker build and tag latest'
        run: |
          ./gradlew clean assemble
          APP_NAME=$(echo $GITHUB_REPOSITORY | rev | cut -f1 -d"/" | rev )
          IMAGE_BASE="ghcr.io/$GITHUB_REPOSITORY/$APP_NAME"
          IMAGE_LATEST="$IMAGE_BASE:latest"
          docker build --tag $IMAGE_LATEST .

      - name: 'Run end-to-end-tests'
        run: |
          cd dittnav-docker-compose
          ./gradlew test
