name: Build & test PR

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/skills/**"
      - ".github/workflows/codeql-scan.yaml"
      - ".github/workflows/deploy.yaml"
      - '.github/workflows/digestabot-automerge.yaml'
      - '.github/workflows/digestabot-update.yaml'
      - ".github/workflows/manual-deploy.yaml"
      - ".github/dependabot.yaml"
      - ".nais/**"

env:
  TZ: Europe/Oslo

jobs:
  build-test-pr:
    permissions:
      contents: read
    name: Build & test application
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@6d597f4b49bff3f5e59833b784eb63aa5ddc8603 # ratchet:navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@v1.0.2
    with:
      has-vitest: true
    secrets: inherit
