name: Digestabot Update

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

env:
  TZ: Europe/Oslo

jobs:
  digestabot-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Digestabot Update
    uses: navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@9f663f4e1ff4f85a52efa067fbf53c5a6bbaede9 # ratchet:navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@v1.1.2
