name: Digestabot Update

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

env:
  TZ: Europe/Oslo

jobs:
  digestabot-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Digestabot Update
    uses: navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@dac7a1ac47e76110d90af301b2152057c215c867 # ratchet:navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@v1.0.0
