name: Digestabot Update

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

env:
  TZ: Europe/Oslo

jobs:
  digestabot-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Digestabot Update
    uses: navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@6d597f4b49bff3f5e59833b784eb63aa5ddc8603 # ratchet:navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@v1.0.2
