name: Deploy application manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - q1
          - qx
env:
  TZ: Europe/Oslo

jobs:
  build-push-image:
    permissions:
      contents: read
      id-token: write
    name: Build application & build/push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image.yaml@main
    secrets: inherit

  deploy-manual:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      deployments: write
    needs: [build-push-image]
    name: Deploy to dev-gcp-${{ inputs.environment }}
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-${{ inputs.environment }}.yaml
      image: ${{ needs.build-push-image.outputs.image }}
